---

- hosts: ub1
  become: yes
  tasks:
  - name: pre wget repo
    apt:
        name: apt-transport-https
        state: latest
  - name: wget repo
    ansible.builtin.get_url:
      url: "https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-4+ubuntu20.04_all.deb"
      dest: "/home/griffon"
  - name: install repo
    apt:
        deb: "{{ item }}"
        with_items:
          - /home/griffon/zabbix-release_6.0-4+ubuntu20.04_all.deb
  - name: Install zabbix-psql on Ubuntu
    apt:
      name: 'zabbix-server-pgsql'
      state: 'latest'
    when:
       ansible_os_family == "Debian"
  - name: Install zabbix-frontend on Ubuntu
    apt:
      name: 'zabbix-frontend-php'
      state: 'latest'
    when:
       ansible_os_family == "Debian"
  - name: Install zabbix etc on Ubuntu
    apt: pkg={{ item }} state=latest
    with_items:
      - apache2
      - php8.1-pgsql
      - zabbix-apache-conf
      - zabbix-sql-scripts
    when:
       ansible_os_family == "Debian"
  - name: set zabbix server config for ubuntu
    ansible.builtin.script: /etc/ansible/roles/set_zabbix_server.sh
    when:
       ansible_os_family == "Debian"
  - name: zabbix-server restart
    ansible.builtin.service:
      name: zabbix-server
      state: restarted
      enabled: true
  handlers:
  - name: zabbix-server systemd
    systemd:
     name: zabbix-server.service
     enabled: yes
     state: started
